# Actions train a model on Azure Machine Learning
name: aml-model-monitor

on:
  push:
    branches:
      - monitor-via-aml
    # paths:
    #   - 'code/*'

jobs:
  job1:    # job name
    runs-on: ubuntu-latest
    steps:
    # Checking out repository
    - name: Check Out Repository
      id: checkout_repository
      uses: actions/checkout@v2

    # - name: Set up Python 3.x                               
    #   uses: actions/setup-python@v2                               
    #   with:                                 
    #     python-version: '3.x'
    
    # - name: Install python packages
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install -r code/track/requirement.txt
    
    # Monitoring Model
    # - name: Monitor current Model by executing python script
    #   id: monitor_model
    #   env:
    #     azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    #   run: python code/track/track.py

    # Connect with Azure workspace
    - name: Connect/Create Azure Machine Learning Workspace
      id: aml_workspace
      uses: Azure/aml-workspace@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Connecting to Azure Compute instance
    - name: Connect/Create Azure Machine Learning Compute Target
      id: aml_compute_training
      uses: Azure/aml-compute@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Submit a monitoring run to AML
    - name: Submit model monitoring run
      id: aml_monitor_run
      uses: Azure/aml-run@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          # optional
          parameters_file: "monitor-run.json"
    
    - name: Add fresh_data_accuracy to Github Env
      run: |
            dict="${{steps.aml_monitor_run.outputs.run_metrics}}"
            echo "------ Truth ------"
            echo ${{steps.aml_monitor_run.outputs.run_metrics}}
            
            echo "------ Extracting ------"
            echo $dict | sed 's/.*://' | grep -Eo '[+-]?[0-9]+([.][0-9]+)?'
            echo "------ Extracting ------"
            new_accuracy=$(echo $dict | sed 's/.*://' | grep -Eo '[+-]?[0-9]+([.][0-9]+)?')
            echo $new_accuracy
            echo "fresh_data_accuracy_env=$new_accuracy" >> $GITHUB_ENV
    
    - name: Debugging next steps
      run: |
            echo "--- check if variable is accesible in next step ------"
            echo $fresh_data_accuracy_env

    # Submit a training run to the Azure Machine Learning
    - name: Submit model re-training run
      if: $fresh_data_accuracy_env < 0.8
      id: aml_new_model_run
      uses: Azure/aml-run@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Add model_accuracy to Github Env
      run: |
            dict="${{steps.aml_new_model_run.outputs.run_metrics}}"
            echo "------ Truth ------"
            echo ${{steps.aml_new_model_run.outputs.run_metrics}}
            
            echo "------ Extracting ------"
            echo $dict | sed 's/.*://' | grep -Eo '[+-]?[0-9]+([.][0-9]+)?'
            echo "------ Extracting ------"
            new_model_accuracy=$(echo $dict | sed 's/.*://' | grep -Eo '[+-]?[0-9]+([.][0-9]+)?')
            echo $new_model_accuracy
            echo "model_accuracy_env=$new_model_accuracy" >> $GITHUB_ENV

    # Register model in Azure Machine Learning model registry
    - name: Register model
      if: $model_accuracy_env > $fresh_data_accuracy_env
      id: aml_registermodel
      uses: Azure/aml-registermodel@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          run_id:  ${{ steps.aml_new_model_run.outputs.run_id }}
          experiment_name: ${{ steps.aml_new_model_run.outputs.experiment_name }}
          # optional
          parameters_file: "monitor-register.json"

    # Deploy model in Azure Machine Learning to ACI
    - name: Deploy model
      if: $model_accuracy_env > $fresh_data_accuracy_env
      id: aml_deploy
      uses: Azure/aml-deploy@v1
      with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
          model_name:  ${{ steps.aml_registermodel.outputs.model_name }}
          model_version: ${{ steps.aml_registermodel.outputs.model_version }}
          # optional
          parameters_file: "monitor-deploy.json"